// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvdmrfrnvbtgethynjtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZG1yZnJudmJ0Z2V0aHluanRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMzEwOTgsImV4cCI6MjA2MzkwNzA5OH0.Puz3-IxSp-NmsZ8n3Mnn__DcOdHI0ydT5Oa6IhH-C4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);